"use client";

import { Suspense, useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Clock3, Edit3, Globe2, Heart, LockKeyhole, MessageCircleHeart, Sparkles, Star, ThumbsUp } from "lucide-react";

type Step = "welcome" | "rate" | "feedback" | "generating" | "suggestions" | "questions" | "review" | "google" | "thanks";
type QuestionAnswers = { highlight: string; moment: string; recommend: string };
type ConfiguredQuestion = { id: string; text: string; type: string; isRequired: boolean; options: Array<{ id: string; label: string; value: string }> };
type Language = "English" | "Hindi" | "Marathi" | "Minglish" | "Hinglish";

const languageOptions: Array<{ value: Language; label: string }> = [
  { value: "English", label: "English" },
  { value: "Hindi", label: "हिंदी" },
  { value: "Marathi", label: "मराठी" },
  { value: "Minglish", label: "Minglish" },
  { value: "Hinglish", label: "Hinglish" },
];

const translations: Record<Language, { welcome: string; welcomeCopy: string; start: string; rate: string; rateCopy: string; feedback: string; feedbackCopy: string; generating: string; generatingCopy: string; suggestions: string; suggestionsCopy: string; own: string; questions: string; questionsCopy: string; review: string; reviewCopy: string; continue: string; private: string; google: string; thanks: string; done: string }> = {
  English: { welcome: "How was your stay?", welcomeCopy: "Your honest experience helps us create more thoughtful stays for every guest.", start: "Share your experience", rate: "How was your overall experience?", rateCopy: "There’s no right answer. Just your honest one.", feedback: "What stood out to you?", feedbackCopy: "Pick anything that felt special. A few words go a long way.", generating: "Finding five ways to say it...", generatingCopy: "We’re turning only what you shared into review options you can choose from or edit.", suggestions: "Five ways to say it.", suggestionsCopy: "Pick the one that sounds most like you. You can edit it next.", own: "I’ll write my own review", questions: "Three quick questions.", questionsCopy: "Answer as much as you like. We’ll turn your thoughts into a draft you control.", review: "Ready to share?", reviewCopy: "Make any changes you’d like. You’re always in control.", continue: "Continue to Google", private: "Want to share privately with the business?", google: "Ready to share your experience?", thanks: "Your voice matters.", done: "Done" },
  Hindi: { welcome: "आपका ठहरना कैसा रहा?", welcomeCopy: "आपका सच्चा अनुभव हर मेहमान के लिए बेहतर ठहरने में हमारी मदद करता है।", start: "अपना अनुभव साझा करें", rate: "आपका कुल अनुभव कैसा रहा?", rateCopy: "सही या गलत जवाब नहीं है। बस अपना सच्चा अनुभव बताएं।", feedback: "आपको सबसे अच्छा क्या लगा?", feedbackCopy: "जो खास लगा उसे चुनें। कुछ शब्द भी बहुत मायने रखते हैं।", generating: "कहने के पांच तरीके खोज रहे हैं...", generatingCopy: "आपने जो साझा किया है, उसी से समीक्षा के विकल्प बनाए जा रहे हैं।", suggestions: "कहने के पांच तरीके।", suggestionsCopy: "जो आपकी आवाज़ जैसा लगे उसे चुनें। आगे इसे बदल सकते हैं।", own: "मैं अपनी समीक्षा खुद लिखूंगा", questions: "तीन छोटे सवाल।", questionsCopy: "जितना चाहें बताएं। हम आपके विचारों से एक ड्राफ्ट बनाएंगे।", review: "साझा करने के लिए तैयार?", reviewCopy: "जो बदलना चाहें बदलें। नियंत्रण हमेशा आपका है।", continue: "Google पर जारी रखें", private: "व्यवसाय के साथ निजी तौर पर साझा करें?", google: "अपना अनुभव साझा करने के लिए तैयार?", thanks: "आपकी आवाज़ मायने रखती है।", done: "हो गया" },
  Marathi: { welcome: "तुमचा मुक्काम कसा होता?", welcomeCopy: "तुमचा प्रामाणिक अनुभव प्रत्येक पाहुण्यासाठी अधिक चांगला मुक्काम तयार करण्यात आम्हाला मदत करतो.", start: "तुमचा अनुभव शेअर करा", rate: "तुमचा एकूण अनुभव कसा होता?", rateCopy: "योग्य किंवा चुकीचे उत्तर नाही. फक्त तुमचा प्रामाणिक अनुभव सांगा.", feedback: "तुमच्या लक्षात काय राहिले?", feedbackCopy: "जे खास वाटले ते निवडा. काही शब्दही खूप उपयोगी ठरतात.", generating: "सांगण्याचे पाच मार्ग शोधत आहोत...", generatingCopy: "तुम्ही शेअर केलेल्या माहितीवरूनच पुनरावलोकनाचे पर्याय तयार करत आहोत.", suggestions: "सांगण्याचे पाच मार्ग.", suggestionsCopy: "तुमच्यासारखे वाटणारे वाक्य निवडा. पुढे ते बदलता येईल.", own: "मी माझे पुनरावलोकन स्वतः लिहीन", questions: "तीन छोटे प्रश्न.", questionsCopy: "तुम्हाला जितके सांगायचे असेल तितके सांगा. तुमच्या विचारांचा मसुदा तयार करू.", review: "शेअर करण्यासाठी तयार?", reviewCopy: "हवे ते बदल करा. नियंत्रण नेहमी तुमचे आहे.", continue: "Google वर पुढे जा", private: "व्यवसायासोबत खासगीपणे शेअर करायचे आहे?", google: "तुमचा अनुभव शेअर करण्यासाठी तयार?", thanks: "तुमचा आवाज महत्त्वाचा आहे.", done: "पूर्ण" },
  Minglish: { welcome: "Tumcha stay kasa hota?", welcomeCopy: "Tumcha honest experience pratyek guest sathi better stay tayar karayla amhala help karto.", start: "Tumcha experience share kara", rate: "Tumcha overall experience kasa hota?", rateCopy: "Right or wrong answer nahi. Fakt tumcha honest experience sanga.", feedback: "Tumhala saglyat jast kay avadla?", feedbackCopy: "Je special vatla te select kara. Thode words pan khup matter kartat.", generating: "Sangnyache paach ways shodhat aahot...", generatingCopy: "Tumhi share kelelya goshtinvarunch review options tayar karat aahot.", suggestions: "Sangnyache paach ways.", suggestionsCopy: "Tumchya voice sarkha vatnara option nivda. Nantar edit karta yeil.", own: "Mi maza review swatah lihin", questions: "Teen quick questions.", questionsCopy: "Jevdha sangaycha asel tevdha sanga. Tumchya thoughts cha draft banavu.", review: "Share karayla ready?", reviewCopy: "Hava to change kara. Control nehmi tumchach aahe.", continue: "Google var continue kara", private: "Business sobat private share karaycha aahe?", google: "Tumcha experience share karayla ready?", thanks: "Tumcha voice important aahe.", done: "Done" },
  Hinglish: { welcome: "Aapka stay kaisa raha?", welcomeCopy: "Aapka honest experience har guest ke liye better stay banane mein humari help karta hai.", start: "Apna experience share karein", rate: "Aapka overall experience kaisa raha?", rateCopy: "Koi right ya wrong answer nahi. Bas apna honest experience batayein.", feedback: "Aapko sabse zyada kya accha laga?", feedbackCopy: "Jo special laga woh choose karein. Kuch words bhi kaafi hote hain.", generating: "Kehne ke paanch tareeke dhoond rahe hain...", generatingCopy: "Aapne jo share kiya hai, sirf usi se review options bana rahe hain.", suggestions: "Kehne ke paanch tareeke.", suggestionsCopy: "Jo aapki voice jaisa lage use choose karein. Baad mein edit kar sakte hain.", own: "Main apna review khud likhunga", questions: "Teen quick questions.", questionsCopy: "Jitna batana chahein batayein. Aapke thoughts se draft banega.", review: "Share karne ke liye ready?", reviewCopy: "Jo change karna ho karein. Control hamesha aapka hai.", continue: "Google par continue karein", private: "Business ke saath privately share karna hai?", google: "Apna experience share karne ke liye ready?", thanks: "Aapki voice matter karti hai.", done: "Done" },
};

type BusinessConfig = { name: string; location: string; initial: string; googleReviewUrl: string };
function useQrBusiness() {
  const searchParams = useSearchParams();
  const qrCode = searchParams.get("qr");
  const [assignedBusiness, setAssignedBusiness] = useState<BusinessConfig | null>(null);
  useEffect(() => {
    if (!qrCode) return;
    fetch(`/api/public/qr/${encodeURIComponent(qrCode)}`).then((response) => response.ok ? response.json() : null).then((data: { business?: BusinessConfig } | null) => {
      if (data?.business) setAssignedBusiness(data.business);
    }).catch(() => undefined);
  }, [qrCode]);
  return assignedBusiness;
}
const ratings = [{ value: 1, emoji: "😞", label: "Very poor" }, { value: 2, emoji: "😕", label: "Poor" }, { value: 3, emoji: "😐", label: "Okay" }, { value: 4, emoji: "🙂", label: "Good" }, { value: 5, emoji: "😍", label: "Excellent" }];
const themes = ["Room", "Cleanliness", "Staff", "Hospitality", "Location", "Food", "Amenities"];
const themeTranslations: Partial<Record<Language, Record<string, string>>> = {
  Hindi: { Room: "कमरा", Cleanliness: "साफ-सफाई", Staff: "स्टाफ", Hospitality: "आतिथ्य", Location: "स्थान", Food: "खाना", Amenities: "सुविधाएं" },
  Marathi: { Room: "खोली", Cleanliness: "स्वच्छता", Staff: "कर्मचारी", Hospitality: "आदरातिथ्य", Location: "ठिकाण", Food: "जेवण", Amenities: "सुविधा" },
  Hinglish: { Room: "Room", Cleanliness: "Cleanliness", Staff: "Staff", Hospitality: "Hospitality", Location: "Location", Food: "Food", Amenities: "Facilities" },
  Minglish: { Room: "Room", Cleanliness: "Cleanliness", Staff: "Staff", Hospitality: "Hospitality", Location: "Location", Food: "Jevan", Amenities: "Suvidha" },
};
const uiText: Partial<Record<Language, Record<string, string>>> = {
  Hindi: { "A little note from us": "हमारी ओर से एक छोटा सा संदेश", "Be heard": "अपनी बात रखें", "Shape better stays": "बेहतर ठहरने में मदद करें", "Keep it honest": "ईमानदार रहें", "Takes less than a minute": "एक मिनट से भी कम समय लगेगा", "First, a feeling": "सबसे पहले, अपनी भावना बताएं", "Very poor": "बहुत खराब", Poor: "खराब", Okay: "ठीक", Good: "अच्छा", Excellent: "बहुत अच्छा", "Your feedback helps us grow, whatever the rating.": "आपकी रेटिंग चाहे जो हो, आपकी प्रतिक्रिया हमें बेहतर बनने में मदद करती है।", "A little more detail": "थोड़ा और बताएं", "Anything else you’d like to share?": "क्या आप कुछ और साझा करना चाहेंगे?", Optional: "वैकल्पिक", "What could we have done better?": "हम और बेहतर क्या कर सकते थे?", "What made your stay memorable?": "आपका ठहरना यादगार किस वजह से बना?", "Only share what feels comfortable.": "सिर्फ वही साझा करें जिसमें आप सहज हों।", "See 5 AI review drafts": "AI की 5 समीक्षा ड्राफ्ट देखें", "One moment": "एक क्षण", "Choose your voice": "अपनी शैली चुनें", "Your words first": "पहले आपके शब्द", "What stood out most?": "सबसे खास क्या लगा?", "Was there a moment you remember?": "क्या कोई यादगार पल था?", "Would you recommend this business?": "क्या आप इस व्यवसाय की सिफारिश करेंगे?", "Build my review": "मेरी समीक्षा बनाएं", "Your words, polished": "आपके शब्द, बेहतर रूप में", "Your review": "आपकी समीक्षा", "Drafted from your feedback": "आपकी प्रतिक्रिया से तैयार", "Written from your answers": "आपके जवाबों से लिखी गई", "AI helps with the words. The experience is yours.": "AI शब्दों में मदद करता है। अनुभव आपका है।", "No AI wording was added beyond your answers.": "आपके जवाबों के अलावा कोई AI शब्द नहीं जोड़ा गया।", "You’ll review and post it yourself on Google.": "आप Google पर खुद समीक्षा देखकर पोस्ट करेंगे।", "Almost there": "बस थोड़ा और", "Review on Google": "Google पर समीक्षा", "Open Google Review": "Google समीक्षा खोलें", "Google opens in a new tab. You can come back here anytime.": "Google नए टैब में खुलेगा। आप कभी भी वापस आ सकते हैं।", "Thank you": "धन्यवाद", "With gratitude,": "आभार सहित,", "A private note": "एक निजी संदेश", "Help us make it right.": "हमें इसे बेहतर करने में मदद करें।", "Your note goes directly to the business team and won’t be posted publicly.": "आपका संदेश सीधे व्यवसाय की टीम तक जाएगा और सार्वजनिक रूप से पोस्ट नहीं होगा।", "Your name (optional)": "आपका नाम (वैकल्पिक)", "Email or phone (optional)": "ईमेल या फोन (वैकल्पिक)", "Send privately": "निजी तौर पर भेजें" },
  Marathi: { "A little note from us": "आमच्याकडून एक छोटीशी नोंद", "Be heard": "तुमचे मत मांडा", "Shape better stays": "चांगला मुक्काम घडवण्यास मदत करा", "Keep it honest": "प्रामाणिक रहा", "Takes less than a minute": "एका मिनिटापेक्षा कमी वेळ लागेल", "First, a feeling": "सर्वप्रथम तुमची भावना सांगा", "Very poor": "खूप खराब", Poor: "खराब", Okay: "ठीक", Good: "चांगले", Excellent: "उत्कृष्ट", "Your feedback helps us grow, whatever the rating.": "तुमचे अभिप्राय आम्हाला सुधारण्यास मदत करतात, रेटिंग काहीही असो.", "A little more detail": "थोडे अधिक सांगा", "Anything else you’d like to share?": "तुम्हाला आणखी काही शेअर करायचे आहे का?", Optional: "ऐच्छिक", "What could we have done better?": "आम्ही आणखी चांगले काय करू शकलो असतो?", "What made your stay memorable?": "तुमचा मुक्काम संस्मरणीय कशामुळे झाला?", "Only share what feels comfortable.": "ज्यात तुम्हाला सोयीचे वाटते तेवढेच शेअर करा.", "See 5 AI review drafts": "AI चे 5 पुनरावलोकन मसुदे पहा", "One moment": "एक क्षण", "Choose your voice": "तुमची शैली निवडा", "Your words first": "प्रथम तुमचे शब्द", "What stood out most?": "सर्वात खास काय वाटले?", "Was there a moment you remember?": "आठवणीत राहिलेला एखादा क्षण होता का?", "Would you recommend this business?": "तुम्ही या व्यवसायाची शिफारस कराल का?", "Build my review": "माझे पुनरावलोकन तयार करा", "Your words, polished": "तुमचे शब्द, सुधारलेले", "Your review": "तुमचे पुनरावलोकन", "Drafted from your feedback": "तुमच्या अभिप्रायातून तयार", "Written from your answers": "तुमच्या उत्तरांमधून लिहिलेले", "AI helps with the words. The experience is yours.": "AI शब्दांमध्ये मदत करते. अनुभव तुमचा आहे.", "No AI wording was added beyond your answers.": "तुमच्या उत्तरांव्यतिरिक्त कोणतेही AI शब्द जोडलेले नाहीत.", "You’ll review and post it yourself on Google.": "तुम्ही Google वर स्वतः पुनरावलोकन पाहून पोस्ट कराल.", "Almost there": "बस थोडेच बाकी", "Review on Google": "Google वर पुनरावलोकन", "Open Google Review": "Google पुनरावलोकन उघडा", "Google opens in a new tab. You can come back here anytime.": "Google नवीन टॅबमध्ये उघडेल. तुम्ही कधीही परत येऊ शकता.", "Thank you": "धन्यवाद", "With gratitude,": "कृतज्ञतेसह,", "A private note": "एक खासगी संदेश", "Help us make it right.": "आम्हाला हे सुधारण्यास मदत करा.", "Your note goes directly to the business team and won’t be posted publicly.": "तुमचा संदेश थेट व्यवसायाच्या टीमकडे जाईल आणि सार्वजनिकपणे पोस्ट केला जाणार नाही.", "Your name (optional)": "तुमचे नाव (ऐच्छिक)", "Email or phone (optional)": "ईमेल किंवा फोन (ऐच्छिक)", "Send privately": "खासगीपणे पाठवा" },
  Hinglish: { "A little note from us": "Humari taraf se ek chhota note", "Be heard": "Apni baat rakhein", "Shape better stays": "Better stays banane mein help karein", "Keep it honest": "Honest rakhein", "Takes less than a minute": "Ek minute se bhi kam lagega", "First, a feeling": "Pehle apni feeling batayein", "Very poor": "Bahut kharab", Poor: "Kharab", Okay: "Theek", Good: "Accha", Excellent: "Bahut accha", "Your feedback helps us grow, whatever the rating.": "Aapka feedback humein better banne mein help karta hai, rating chahe jo ho.", "A little more detail": "Thoda aur batayein", "Anything else you’d like to share?": "Kuch aur share karna chahenge?", Optional: "Optional", "What could we have done better?": "Hum aur better kya kar sakte the?", "What made your stay memorable?": "Aapka stay memorable kis wajah se bana?", "Only share what feels comfortable.": "Sirf wahi share karein jismein aap comfortable hain.", "See 5 AI review drafts": "AI ke 5 review drafts dekhein", "One moment": "Ek moment", "Choose your voice": "Apni voice choose karein", "Your words first": "Pehle aapke words", "What stood out most?": "Sabse special kya laga?", "Was there a moment you remember?": "Koi memorable moment yaad hai?", "Would you recommend this business?": "Kya aap is business ko recommend karenge?", "Build my review": "Mera review banayein", "Your words, polished": "Aapke words, polished", "Your review": "Aapka review", "Drafted from your feedback": "Aapke feedback se drafted", "Written from your answers": "Aapke answers se written", "AI helps with the words. The experience is yours.": "AI words mein help karta hai. Experience aapka hai.", "No AI wording was added beyond your answers.": "Aapke answers ke alawa AI wording add nahi hui.", "You’ll review and post it yourself on Google.": "Aap Google par khud review karke post karenge.", "Almost there": "Bas thoda aur", "Review on Google": "Google par review", "Open Google Review": "Google review kholein", "Google opens in a new tab. You can come back here anytime.": "Google naye tab mein khulega. Aap kabhi bhi wapas aa sakte hain.", "Thank you": "Thank you", "With gratitude,": "Gratitude ke saath,", "A private note": "Ek private note", "Help us make it right.": "Humein ise better banane mein help karein.", "Your note goes directly to the business team and won’t be posted publicly.": "Aapka note directly business team ko jayega aur public post nahi hoga.", "Your name (optional)": "Aapka naam (optional)", "Email or phone (optional)": "Email ya phone (optional)", "Send privately": "Privately bhejein" },
  Minglish: { "A little note from us": "Amchyakadun ek choti note", "Be heard": "Tumcha voice share kara", "Shape better stays": "Better stays banvayla help kara", "Keep it honest": "Honest theva", "Takes less than a minute": "Ek minute peksha kami vel lagel", "First, a feeling": "Pahile tumchi feeling sanga", "Very poor": "Khup kharab", Poor: "Kharab", Okay: "Thik", Good: "Chan", Excellent: "Khup chan", "Your feedback helps us grow, whatever the rating.": "Tumcha feedback amhala improve vhayla help karto, rating kahi hi aso.", "A little more detail": "Thoda ajun sanga", "Anything else you’d like to share?": "Ajun kahi share karaycha aahe ka?", Optional: "Optional", "What could we have done better?": "Amhi ajun better kay karu shaklo asto?", "What made your stay memorable?": "Tumcha stay memorable kashamule zala?", "Only share what feels comfortable.": "Jevdha comfortable vatat tevढhach share kara.", "See 5 AI review drafts": "AI che 5 review drafts paha", "One moment": "Ek moment", "Choose your voice": "Tumchi style nivda", "Your words first": "Pahile tumche words", "What stood out most?": "Saglyat special kay vatla?", "Was there a moment you remember?": "Konta memorable moment lakshat aahe ka?", "Would you recommend this business?": "Tumhi ya business chi recommendation karal ka?", "Build my review": "Maza review banva", "Your words, polished": "Tumche words, polished", "Your review": "Tumcha review", "Drafted from your feedback": "Tumchya feedback madhun drafted", "Written from your answers": "Tumchya answers madhun written", "AI helps with the words. The experience is yours.": "AI words madhe help karto. Experience tumchach aahe.", "No AI wording was added beyond your answers.": "Tumchya answers vyatirikta AI wording add keli nahi.", "You’ll review and post it yourself on Google.": "Tumhi Google var swatah review karun post karal.", "Almost there": "Bas thodach baki", "Review on Google": "Google var review", "Open Google Review": "Google review ughda", "Google opens in a new tab. You can come back here anytime.": "Google navin tab madhe ughdel. Tumhi kadhihi parat yeu shakta.", "Thank you": "Thank you", "With gratitude,": "Gratitude sobat,", "A private note": "Ek private note", "Help us make it right.": "Amhala he better karayla help kara.", "Your note goes directly to the business team and won’t be posted publicly.": "Tumcha note direct business team kade jail ani public post honar nahi.", "Your name (optional)": "Tumcha nav (optional)", "Email or phone (optional)": "Email kiwa phone (optional)", "Send privately": "Private pathva" },
};
const translate = (language: Language, value: string) => uiText[language]?.[value] || value;
const translateTheme = (language: Language, value: string) => themeTranslations[language]?.[value] || value;

export default function Home() { return <Suspense fallback={<main className="customer-shell" /> }><HomeContent /></Suspense>; }

function HomeContent() {
  const searchParams = useSearchParams();
  const qrCode = searchParams.get("qr");
  const sessionId = searchParams.get("session");
  const [business, setBusiness] = useState<BusinessConfig | null>(null);
  const [step, setStep] = useState<Step>("welcome");
  const [rating, setRating] = useState(0);
  const [selectedThemes, setSelectedThemes] = useState<string[]>([]);
  const [comment, setComment] = useState("");
  const [review, setReview] = useState("");
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [suggestionDrafts, setSuggestionDrafts] = useState<Array<{ id: string; content: string }>>([]);
  const [answers, setAnswers] = useState<QuestionAnswers>({ highlight: "", moment: "", recommend: "" });
  const [configuredQuestions, setConfiguredQuestions] = useState<ConfiguredQuestion[]>([]);
  const [questionResponses, setQuestionResponses] = useState<Record<string, string[]>>({});
  const [language, setLanguage] = useState<Language>("English");
  const copy = translations[language];
  const [showPrivate, setShowPrivate] = useState(false);

  useEffect(() => {
    if (!qrCode) return;
    fetch(`/api/public/qr/${encodeURIComponent(qrCode)}`).then((response) => response.ok ? response.json() : null).then((data: { business?: { name: string; location: string; initial: string; googleReviewUrl: string } } | null) => {
      if (data?.business) setBusiness(data.business);
    }).catch(() => undefined);
  }, [qrCode]);

  useEffect(() => {
    if (!qrCode || !rating) {
      setConfiguredQuestions([]);
      return;
    }
    const controller = new AbortController();
    fetch(`/api/public/qr/${encodeURIComponent(qrCode)}/questions?rating=${encodeURIComponent(String(rating))}`, { signal: controller.signal })
      .then((response) => response.ok ? response.json() : null)
      .then((data: { questions?: ConfiguredQuestion[] } | null) => setConfiguredQuestions(data?.questions ?? []))
      .catch(() => undefined);
    return () => controller.abort();
  }, [qrCode, rating]);

  useEffect(() => {
    setQuestionResponses({});
  }, [qrCode, rating]);

  if (!qrCode) return <CustomerMessage title="QR Code Not Found" />;
  if (!business) return <CustomerMessage title="This QR Code is not connected to an active business." />;

  const chooseRating = (value: number) => { setRating(value); setStep("feedback"); };
  const toggleTheme = (theme: string) => setSelectedThemes((current) => current.includes(theme) ? current.filter((item) => item !== theme) : [...current, theme]);
  const buildSuggestions = async () => {
    const subject = selectedThemes.length ? selectedThemes.slice(0, 3).join(", ").toLowerCase() : "my stay";
    const detail = comment.trim() || (language === "English" ? `The ${subject} made a real difference to my experience.` : copy.feedbackCopy);
    const opening = rating >= 4 ? `I had a lovely experience at ${business.name}.` : rating === 3 ? `My experience at ${business.name} was mixed.` : `My experience at ${business.name} could have been better.`;
    const fallbackSuggestions = [
      `${opening} ${detail} I appreciated how welcoming everything felt and would happily recommend it to other guests.`,
      `${business.name} gave me a memorable stay. ${detail} The thoughtful service and attention to detail made me feel genuinely looked after.`,
      `A sincere review of ${business.name}: ${detail} There were some highlights and a few areas to improve, but the team made the experience personal.`,
      `I enjoyed my time at ${business.name}, especially the ${subject}. ${detail} It was an easy, comfortable place to spend time.`,
      `Thank you to the team at ${business.name}. ${detail} I am sharing this honestly because guest feedback helps create better stays for everyone.`,
    ];
    setStep("generating");
    try {
      if (!sessionId) throw new Error("Review session is missing");
      const feedbackResponse = await fetch(`/api/review/${encodeURIComponent(sessionId)}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, themes: selectedThemes, comment, language }) });
      if (!feedbackResponse.ok) throw new Error("Unable to save feedback");
      const response = await fetch("/api/generate-reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId, rating, themes: selectedThemes, comment, language }) });
      const data = await response.json() as { reviews?: string[]; drafts?: Array<{ id: string; content: string }> };
      setSuggestionDrafts(data.drafts ?? []);
      setSuggestions(data.reviews?.length === 5 ? data.reviews : fallbackSuggestions);
    } catch {
      setSuggestions(fallbackSuggestions);
    }
    window.setTimeout(() => setStep("suggestions"), 900);
  };
  const createOwnReview = async () => {
    const highlight = answers.highlight.trim() || comment.trim() || `the ${selectedThemes[0]?.toLowerCase() || "stay"}`;
    const moment = answers.moment.trim() ? ` ${answers.moment.trim()}` : "";
    const recommendation = answers.recommend.trim() ? ` ${answers.recommend.trim()}` : "";
    const opening = language === "Hindi" ? `मेरा ${business.name} में अनुभव ${rating >= 4 ? "बहुत अच्छा" : rating === 3 ? "ठीक-ठाक" : "निराशाजनक"} रहा` : language === "Marathi" ? `${business.name} मधील माझा अनुभव ${rating >= 4 ? "खूप छान" : rating === 3 ? "मिश्र" : "निराशाजनक"} होता` : language === "Hinglish" ? `${business.name} mein mera experience ${rating >= 4 ? "bahut accha" : rating === 3 ? "mixed" : "disappointing"} raha` : language === "Minglish" ? `${business.name} madhla maza experience ${rating >= 4 ? "khup chan" : rating === 3 ? "mixed" : "disappointing"} hota` : `I had a ${rating >= 4 ? "great" : rating === 3 ? "mixed" : "disappointing"} experience at ${business.name}`;
    setReview(`${opening}. ${highlight}.${moment}${recommendation}`);
    if (sessionId) {
      await fetch(`/api/review/${encodeURIComponent(sessionId)}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, themes: selectedThemes, comment, highlight: answers.highlight, moment: answers.moment, recommendationText: answers.recommend, responses: Object.entries(questionResponses).map(([questionId, values]) => ({ questionId, answers: values })), language }) });
      const draftResponse = await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "manual", content: `${opening}. ${highlight}.${moment}${recommendation}`, language }) });
      const draftData = await draftResponse.json().catch(() => ({})) as { draft?: { id: string } };
      if (draftData.draft?.id) await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draftId: draftData.draft.id }) });
    }
    setStep("review");
  };
  const chooseDraft = async (value: string, index: number) => {
    if (sessionId) {
      const existingDraft = suggestionDrafts[index];
      if (existingDraft) await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draftId: existingDraft.id }) });
      else {
        const draftResponse = await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "manual", content: value, language }) });
        const draftData = await draftResponse.json().catch(() => ({})) as { draft?: { id: string } };
        if (draftData.draft?.id) await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draftId: draftData.draft.id }) });
      }
    }
    setReview(value);
    setStep("review");
  };
  const openGoogle = async () => { if (sessionId && review.trim()) { const draftResponse = await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "manual", content: review, language }) }); const draftData = await draftResponse.json().catch(() => ({})) as { draft?: { id: string } }; if (draftData.draft?.id) await fetch(`/api/review/${encodeURIComponent(sessionId)}/drafts`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draftId: draftData.draft.id }) }); await fetch(`/api/review/${encodeURIComponent(sessionId)}/google-click`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); } window.open(business.googleReviewUrl, "_blank", "noopener,noreferrer"); setStep("thanks"); };
  const goBack = () => { if (step === "rate") setStep("welcome"); if (step === "feedback") setStep("rate"); if (step === "suggestions" || step === "questions") setStep("feedback"); if (step === "review") setStep(suggestions.length ? "suggestions" : "questions"); if (step === "google") setStep("review"); };
  const progressStep = step === "rate" ? 1 : step === "feedback" ? 2 : 3;

  return <main className="customer-shell"><div className="ambient-photo" /><div className="ambient-grid" /><header className="topbar"><Link className="brand" href="/" aria-label="Kindred home"><span className="brand-mark"><Heart size={15} fill="currentColor" /></span>kindred</Link><div className="topbar-actions"><label className="language-control"><Globe2 size={15} /><select value={language} onChange={(event) => setLanguage(event.target.value as Language)} aria-label="Choose language">{languageOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown size={13} /></label></div></header><section className={`review-card ${step === "welcome" ? "welcome-card" : ""}`}><AnimatePresence mode="wait" initial={false}><motion.div key={step} className="step-stage" initial={{ opacity: 0, y: 18, filter: "blur(7px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} exit={{ opacity: 0, y: -12, filter: "blur(5px)" }} transition={{ duration: 0.32, ease: [0.22, 1, 0.36, 1] }}>{step !== "welcome" && step !== "thanks" && <button className="back-button" onClick={goBack} aria-label="Go back"><ArrowLeft size={18} /></button>}{step !== "welcome" && step !== "generating" && step !== "thanks" && <Progress step={progressStep} copy={copy} language={language} />}{step === "welcome" && <Welcome copy={copy} language={language} onStart={() => setStep("rate")} />}{step === "rate" && <Rate copy={copy} language={language} rating={rating} onRate={chooseRating} />}{step === "feedback" && <Feedback copy={copy} language={language} selectedThemes={selectedThemes} toggleTheme={toggleTheme} comment={comment} setComment={setComment} rating={rating} onContinue={buildSuggestions} />}{step === "generating" && <Generating copy={copy} language={language} />}{step === "suggestions" && <Suggestions copy={copy} language={language} suggestions={suggestions} onSelect={chooseDraft} onWriteOwn={() => setStep("questions")} />}{step === "questions" && <Questions copy={copy} language={language} answers={answers} setAnswers={setAnswers} configuredQuestions={configuredQuestions} questionResponses={questionResponses} setQuestionResponses={setQuestionResponses} onContinue={createOwnReview} />}{step === "review" && <Review copy={copy} language={language} review={review} setReview={setReview} rating={rating} isAi={suggestions.length > 0} onContinue={() => setStep("google")} onPrivate={() => setShowPrivate(true)} />}{step === "google" && <GoogleHandoff copy={copy} language={language} onContinue={openGoogle} />}{step === "thanks" && <Thanks copy={copy} language={language} onDone={() => setStep("welcome")} />}</motion.div></AnimatePresence></section><div className="footer-note"><LockKeyhole size={14} /> Your feedback is private, secure, and always yours.</div>{showPrivate && <PrivateFeedback sessionId={sessionId} language={language} onClose={() => setShowPrivate(false)} />}</main>;
}

function CustomerMessage({ title }: { title: string }) { return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24, fontFamily: "Arial, sans-serif", color: "#1e2924", textAlign: "center" }}><div><h1>{title}</h1><p>Please scan a valid business QR code to continue.</p></div></main>; }
function Progress({ step, copy, language }: { step: number; copy: typeof translations.English; language: Language }) { return <div className="progress-wrap"><div className="progress-label"><span>{copy.review}</span><strong>{translate(language, "Step")} {step} {translate(language, "of")} 3</strong></div><div className="progress-track"><span style={{ width: `${step * 33.33}%` }} /></div></div>; }
function Welcome({ onStart, copy, language }: { onStart: () => void; copy: typeof translations.English; language: Language }) { const business = useQrBusiness(); if (!business) return null; return <div className="welcome-content"><div className="business-pill"><span className="hotel-monogram">{business.initial}</span><span><b>{business.name}</b><small>{business.location}</small></span><span className="verified-dot"><Check size={12} /></span></div><div className="welcome-hero"><div className="wave-icon">👋</div><p className="eyebrow">{translate(language, "A little note from us")}</p><h1>{copy.welcome}</h1><p className="hero-copy">{copy.welcomeCopy}</p></div><div className="benefit-row"><Benefit icon={<Sparkles />} title={translate(language, "Be heard")} /><Benefit icon={<Heart />} title={translate(language, "Shape better stays")} /><Benefit icon={<ThumbsUp />} title={translate(language, "Keep it honest")} /></div><button className="primary-button" onClick={onStart}>{copy.start} <ArrowRight size={18} /></button><p className="welcome-meta"><Clock3 size={14} /> {translate(language, "Takes less than a minute")}</p></div>; }
function Benefit({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="benefit"><span>{icon}</span><small>{title}</small></div>; }
function Rate({ rating, onRate, copy, language }: { rating: number; onRate: (value: number) => void; copy: typeof translations.English; language: Language }) { return <div className="flow-content"><p className="eyebrow">{translate(language, "First, a feeling")}</p><h2>{copy.rate}</h2><p className="section-copy">{copy.rateCopy}</p><div className="rating-list">{ratings.map((item) => <button className={`rating-option ${rating === item.value ? "selected" : ""}`} key={item.value} onClick={() => onRate(item.value)}><span>{item.emoji}</span><b>{translate(language, item.label)}</b><span className="rating-star"><Star size={13} fill="currentColor" /> {item.value}</span></button>)}</div><p className="gentle-note"><MessageCircleHeart size={16} /> {translate(language, "Your feedback helps us grow, whatever the rating.")}</p></div>; }
function Feedback({ selectedThemes, toggleTheme, comment, setComment, rating, onContinue, copy, language }: { selectedThemes: string[]; toggleTheme: (theme: string) => void; comment: string; setComment: (value: string) => void; rating: number; onContinue: () => void; copy: typeof translations.English; language: Language }) { return <div className="flow-content"><p className="eyebrow">{translate(language, "A little more detail")}</p><h2>{copy.feedback}</h2><p className="section-copy">{copy.feedbackCopy}</p><div className="chip-grid">{themes.map((theme) => <button key={theme} className={`theme-chip ${selectedThemes.includes(theme) ? "active" : ""}`} onClick={() => toggleTheme(theme)}>{selectedThemes.includes(theme) && <Check size={14} />}{translateTheme(language, theme)}</button>)}</div><label className="field-label" htmlFor="comment">{translate(language, "Anything else you’d like to share?")} <span>{translate(language, "Optional")}</span></label><textarea id="comment" maxLength={500} value={comment} onChange={(event) => setComment(event.target.value)} placeholder={translate(language, rating <= 2 ? "What could we have done better?" : "What made your stay memorable?")} /><div className="field-meta"><span>{translate(language, "Only share what feels comfortable.")}</span><span>{comment.length}/500</span></div><button className="primary-button" disabled={!selectedThemes.length && !comment.trim()} onClick={onContinue}>{translate(language, "See 5 AI review drafts")} <Sparkles size={17} /></button></div>; }
function Generating({ copy, language }: { copy: typeof translations.English; language: Language }) { return <div className="generating"><div className="sparkle-orbit"><Sparkles size={28} /></div><p className="eyebrow">{translate(language, "One moment")}</p><h2>{copy.generating}</h2><p className="section-copy">{copy.generatingCopy}</p><div className="loading-lines"><i /><i /><i /></div></div>; }
function Suggestions({ suggestions, onSelect, onWriteOwn, copy, language }: { suggestions: string[]; onSelect: (value: string, index: number) => void; onWriteOwn: () => void; copy: typeof translations.English; language: Language }) { return <div className="flow-content suggestions-view"><p className="eyebrow">{translate(language, "Choose your voice")}</p><h2>{copy.suggestions}</h2><p className="section-copy">{copy.suggestionsCopy}</p><div className="suggestion-list">{suggestions.map((suggestion, index) => <button className="suggestion-card" key={suggestion} onClick={() => onSelect(suggestion, index)}><span className="suggestion-number">0{index + 1}</span><span>{suggestion}</span><ArrowRight size={16} /></button>)}</div><button className="secondary-button" onClick={onWriteOwn}><Edit3 size={15} /> {copy.own}</button></div>; }
function Questions({ answers, setAnswers, configuredQuestions, questionResponses, setQuestionResponses, onContinue, copy, language }: { answers: QuestionAnswers; setAnswers: (answers: QuestionAnswers) => void; configuredQuestions: ConfiguredQuestion[]; questionResponses: Record<string, string[]>; setQuestionResponses: (responses: Record<string, string[]>) => void; onContinue: () => void; copy: typeof translations.English; language: Language }) {
  const update = (key: keyof QuestionAnswers, value: string) => setAnswers({ ...answers, [key]: value });
  const updateQuestion = (questionId: string, values: string[]) => setQuestionResponses({ ...questionResponses, [questionId]: values });
  const configuredComplete = configuredQuestions.every((question) => !question.isRequired || Boolean(questionResponses[question.id]?.length));
  return <div className="flow-content questions-view"><p className="eyebrow">{translate(language, "Your words first")}</p><h2>{copy.questions}</h2><p className="section-copy">{copy.questionsCopy}</p>{configuredQuestions.length ? configuredQuestions.map((question) => { const values = questionResponses[question.id] ?? []; const multiple = question.type === "MULTIPLE_CHOICE"; return <div key={question.id}><label className="field-label" htmlFor={`question-${question.id}`}>{question.text}{question.isRequired && <span>Required</span>}</label>{question.options.length ? <select id={`question-${question.id}`} multiple={multiple} value={multiple ? values : values[0] ?? ""} onChange={(event) => updateQuestion(question.id, Array.from(event.target.selectedOptions, (option) => option.value))}>{!multiple && <option value="">Select an answer</option>}{question.options.map((option) => <option key={option.id} value={option.value}>{option.label}</option>)}</select> : question.type === "TEXT" ? <textarea id={`question-${question.id}`} value={values[0] ?? ""} onChange={(event) => updateQuestion(question.id, [event.target.value])} /> : <input id={`question-${question.id}`} type={question.type === "NUMBER" ? "number" : "text"} value={values[0] ?? ""} onChange={(event) => updateQuestion(question.id, [event.target.value])} />}</div>; }) : <><label className="field-label" htmlFor="highlight">{translate(language, "What stood out most?")}</label><input id="highlight" value={answers.highlight} onChange={(event) => update("highlight", event.target.value)} placeholder={translate(language, "The room, the team, the food...")} /><label className="field-label" htmlFor="moment">{translate(language, "Was there a moment you remember?")}</label><textarea id="moment" value={answers.moment} onChange={(event) => update("moment", event.target.value)} placeholder={translate(language, "Tell us what made it memorable.")} /><label className="field-label" htmlFor="recommend">{translate(language, "Would you recommend this business?")}</label><input id="recommend" value={answers.recommend} onChange={(event) => update("recommend", event.target.value)} placeholder={translate(language, "I would recommend it because...")} /></>}<button className="primary-button" disabled={configuredQuestions.length ? !configuredComplete : (!answers.highlight.trim() && !answers.moment.trim() && !answers.recommend.trim())} onClick={onContinue}>{translate(language, "Build my review")} <ArrowRight size={17} /></button></div>;
}
function Review({ review, setReview, rating, onContinue, onPrivate, isAi, copy, language }: { review: string; setReview: (value: string) => void; rating: number; onContinue: () => void; onPrivate: () => void; isAi: boolean; copy: typeof translations.English; language: Language }) { return <div className="flow-content"><div className="review-heading"><div><p className="eyebrow">{translate(language, isAi ? "Your words, polished" : "Your review")}</p><h2>{copy.review} <Sparkles size={20} /></h2></div><span className="sentiment-badge"><Star size={13} fill="currentColor" /> {rating}.0</span></div><p className="section-copy">{copy.reviewCopy}</p><div className="review-editor"><div className="editor-top"><span>{isAi ? <><Sparkles size={14} /> {translate(language, "Drafted from your feedback")}</> : <><Edit3 size={14} /> {translate(language, "Written from your answers")}</>}</span><Edit3 size={15} /></div><textarea value={review} onChange={(event) => setReview(event.target.value)} aria-label={translate(language, "Edit your review")} /></div><p className="editor-note">{translate(language, isAi ? "AI helps with the words. The experience is yours." : "No AI wording was added beyond your answers.")}</p>{rating <= 2 && <button className="private-link" onClick={onPrivate}>{copy.private} <ArrowRight size={15} /></button>}<button className="primary-button" onClick={onContinue}>{copy.continue} <ArrowRight size={18} /></button><p className="disclaimer">{translate(language, "You’ll review and post it yourself on Google.")}</p></div>; }
function GoogleHandoff({ onContinue, copy, language }: { onContinue: () => void; copy: typeof translations.English; language: Language }) { const business = useQrBusiness(); if (!business) return null; return <div className="flow-content handoff"><div className="google-g"><span>G</span></div><p className="eyebrow">{translate(language, "Almost there")}</p><h2>{copy.google}</h2><p className="section-copy">We’ll open Google for {business.name}. Review and post it yourself there.</p><div className="google-preview"><div className="google-avatar">{business.initial}</div><div><b>{business.name}</b><small>{translate(language, "Review on Google")}</small></div><div className="google-stars">★★★★★</div></div><button className="google-button" onClick={onContinue}>{translate(language, "Open Google Review")} <ArrowRight size={17} /></button><p className="disclaimer">{translate(language, "Google opens in a new tab. You can come back here anytime.")}</p></div>; }
function Thanks({ onDone, copy, language }: { onDone: () => void; copy: typeof translations.English; language: Language }) { const business = useQrBusiness(); if (!business) return null; return <div className="thanks"><div className="success-check"><Check size={34} /></div><p className="eyebrow">{translate(language, "Thank you")}</p><h2>{copy.thanks}</h2><p className="section-copy">Your Google review helps {business.name} understand guests a little better.</p><div className="thanks-signature"><span>{translate(language, "With gratitude,")}</span><b>Team {business.name.replace("Hotel ", "")}</b></div><button className="primary-button" onClick={onDone}>{copy.done} <Check size={17} /></button></div>; }
function PrivateFeedback({ sessionId, onClose, language }: { sessionId: string | null; onClose: () => void; language: Language }) { const [message, setMessage] = useState(""); const [customerName, setCustomerName] = useState(""); const [customerContact, setCustomerContact] = useState(""); const submit = async () => { if (sessionId && message.trim()) await fetch(`/api/review/${encodeURIComponent(sessionId)}/private-feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, customerName, customerContact }) }); onClose(); }; return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose} aria-label="Close">×</button><div className="modal-icon"><Heart size={20} /></div><p className="eyebrow">{translate(language, "A private note")}</p><h2>{translate(language, "Help us make it right.")}</h2><p className="section-copy">{translate(language, "Your note goes directly to the business team and won’t be posted publicly.")}</p><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={translate(language, "What could we have done better?")} /><input value={customerName} onChange={(event) => setCustomerName(event.target.value)} placeholder={translate(language, "Your name (optional)")} /><input value={customerContact} onChange={(event) => setCustomerContact(event.target.value)} placeholder={translate(language, "Email or phone (optional)")} /><button className="primary-button" onClick={submit}>{translate(language, "Send privately")} <ArrowRight size={17} /></button></div></div>; }
